version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: 16launcher_back_pg
    environment:
      POSTGRES_USER: authlib_user
      POSTGRES_PASSWORD: authlib_password
      POSTGRES_DB: authlib_db
    ports:
      - "18200:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authlib_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2023-05-04T21-44-30Z.fips
    container_name: 16launcher_back_minio
    ports:
      - "18201:9000"   # API (S3 совместимый)
      - "18202:9001"   # Веб-интерфейс
    environment:
      MINIO_ROOT_USER: petr
      MINIO_ROOT_PASSWORD: petr12345678
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
